### ISSUE TITLE
sample information json file

### ISSUE THREAD

**Issue by crazyhottommy** [slowkow/snakefiles#2]
Hi,

Could you please show me an example file for the json file containing the sample information?
thanks!

Tommy

**Comment by slowkow** [comment]
This script:

https://github.com/slowkow/snakefiles/blob/master/make_samples.py

creates this file:

https://github.com/slowkow/snakefiles/blob/master/samples.json

**Comment by crazyhottommy** [comment]
Thanks, that is helpful.
